Read from file... ../single_utt/sa1.wav
Read from file... ../TextGrid/sa1.TextGrid
Read from file... ../single_utt/sa2.wav
Read from file... ../TextGrid/sa2.TextGrid
Read from file... ../single_utt/si453.wav
Read from file... ../TextGrid/si453.TextGrid
Read from file... ../single_utt/si454.wav
Read from file... ../TextGrid/si454.TextGrid
Read from file... ../single_utt/si455.wav
Read from file... ../TextGrid/si455.TextGrid
Read from file... ../single_utt/si457.wav
Read from file... ../TextGrid/si457.TextGrid
Read from file... ../single_utt/si458.wav
Read from file... ../TextGrid/si458.TextGrid
Read from file... ../single_utt/si460.wav
Read from file... ../TextGrid/si460.TextGrid
Read from file... ../single_utt/si461.wav
Read from file... ../TextGrid/si461.TextGrid
Read from file... ../single_utt/si462.wav
Read from file... ../TextGrid/si462.TextGrid
Read from file... ../single_utt/si463.wav
Read from file... ../TextGrid/si463.TextGrid
Read from file... ../single_utt/si464.wav
Read from file... ../TextGrid/si464.TextGrid
Read from file... ../single_utt/si465.wav
Read from file... ../TextGrid/si465.TextGrid
Read from file... ../single_utt/si466.wav
Read from file... ../TextGrid/si466.TextGrid
Read from file... ../single_utt/si467.wav
Read from file... ../TextGrid/si467.TextGrid
Read from file... ../single_utt/si468.wav
Read from file... ../TextGrid/si468.TextGrid
Read from file... ../single_utt/si470.wav
Read from file... ../TextGrid/si470.TextGrid
Read from file... ../single_utt/si471.wav
Read from file... ../TextGrid/si471.TextGrid
Read from file... ../single_utt/si472.wav
Read from file... ../TextGrid/si472.TextGrid
Read from file... ../single_utt/si473.wav
Read from file... ../TextGrid/si473.TextGrid
Read from file... ../single_utt/si474.wav
Read from file... ../TextGrid/si474.TextGrid
Read from file... ../single_utt/si475.wav
Read from file... ../TextGrid/si475.TextGrid
Read from file... ../single_utt/si476.wav
Read from file... ../TextGrid/si476.TextGrid
Read from file... ../single_utt/si477.wav
Read from file... ../TextGrid/si477.TextGrid
Read from file... ../single_utt/si478.wav
Read from file... ../TextGrid/si478.TextGrid
Read from file... ../single_utt/si479.wav
Read from file... ../TextGrid/si479.TextGrid
Read from file... ../single_utt/si480.wav
Read from file... ../TextGrid/si480.TextGrid
Read from file... ../single_utt/si481.wav
Read from file... ../TextGrid/si481.TextGrid
Read from file... ../single_utt/si482.wav
Read from file... ../TextGrid/si482.TextGrid
Read from file... ../single_utt/si483.wav
Read from file... ../TextGrid/si483.TextGrid
Read from file... ../single_utt/si484.wav
Read from file... ../TextGrid/si484.TextGrid
Read from file... ../single_utt/si485.wav
Read from file... ../TextGrid/si485.TextGrid
Read from file... ../single_utt/si486.wav
Read from file... ../TextGrid/si486.TextGrid
Read from file... ../single_utt/si487.wav
Read from file... ../TextGrid/si487.TextGrid
Read from file... ../single_utt/si489.wav
Read from file... ../TextGrid/si489.TextGrid
Read from file... ../single_utt/si490.wav
Read from file... ../TextGrid/si490.TextGrid
Read from file... ../single_utt/si491.wav
Read from file... ../TextGrid/si491.TextGrid
Read from file... ../single_utt/si493.wav
Read from file... ../TextGrid/si493.TextGrid
Read from file... ../single_utt/si494.wav
Read from file... ../TextGrid/si494.TextGrid
Read from file... ../single_utt/si495.wav
Read from file... ../TextGrid/si495.TextGrid
Read from file... ../single_utt/si496.wav
Read from file... ../TextGrid/si496.TextGrid
Read from file... ../single_utt/si497.wav
Read from file... ../TextGrid/si497.TextGrid
Read from file... ../single_utt/si498.wav
Read from file... ../TextGrid/si498.TextGrid
Read from file... ../single_utt/si499.wav
Read from file... ../TextGrid/si499.TextGrid
Read from file... ../single_utt/si500.wav
Read from file... ../TextGrid/si500.TextGrid
Read from file... ../single_utt/si501.wav
Read from file... ../TextGrid/si501.TextGrid
Read from file... ../single_utt/si502.wav
Read from file... ../TextGrid/si502.TextGrid
Read from file... ../single_utt/si503.wav
Read from file... ../TextGrid/si503.TextGrid
Read from file... ../single_utt/si505.wav
Read from file... ../TextGrid/si505.TextGrid
Read from file... ../single_utt/si506.wav
Read from file... ../TextGrid/si506.TextGrid
Read from file... ../single_utt/si507.wav
Read from file... ../TextGrid/si507.TextGrid
Read from file... ../single_utt/si508.wav
Read from file... ../TextGrid/si508.TextGrid
Read from file... ../single_utt/si509.wav
Read from file... ../TextGrid/si509.TextGrid
Read from file... ../single_utt/si510.wav
Read from file... ../TextGrid/si510.TextGrid
Read from file... ../single_utt/si511.wav
Read from file... ../TextGrid/si511.TextGrid
Read from file... ../single_utt/si512.wav
Read from file... ../TextGrid/si512.TextGrid
Read from file... ../single_utt/si513.wav
Read from file... ../TextGrid/si513.TextGrid
Read from file... ../single_utt/si514.wav
Read from file... ../TextGrid/si514.TextGrid
Read from file... ../single_utt/si516.wav
Read from file... ../TextGrid/si516.TextGrid
Read from file... ../single_utt/si517.wav
Read from file... ../TextGrid/si517.TextGrid
Read from file... ../single_utt/si519.wav
Read from file... ../TextGrid/si519.TextGrid
Read from file... ../single_utt/si520.wav
Read from file... ../TextGrid/si520.TextGrid
Read from file... ../single_utt/si521.wav
Read from file... ../TextGrid/si521.TextGrid
Read from file... ../single_utt/si522.wav
Read from file... ../TextGrid/si522.TextGrid
Read from file... ../single_utt/si523.wav
Read from file... ../TextGrid/si523.TextGrid
Read from file... ../single_utt/si524.wav
Read from file... ../TextGrid/si524.TextGrid
Read from file... ../single_utt/si525.wav
Read from file... ../TextGrid/si525.TextGrid
Read from file... ../single_utt/si526.wav
Read from file... ../TextGrid/si526.TextGrid
Read from file... ../single_utt/si527.wav
Read from file... ../TextGrid/si527.TextGrid
Read from file... ../single_utt/si528.wav
Read from file... ../TextGrid/si528.TextGrid
Read from file... ../single_utt/si529.wav
Read from file... ../TextGrid/si529.TextGrid
Read from file... ../single_utt/si530.wav
Read from file... ../TextGrid/si530.TextGrid
Read from file... ../single_utt/si531.wav
Read from file... ../TextGrid/si531.TextGrid
Read from file... ../single_utt/si532.wav
Read from file... ../TextGrid/si532.TextGrid
Read from file... ../single_utt/si533.wav
Read from file... ../TextGrid/si533.TextGrid
Read from file... ../single_utt/si534.wav
Read from file... ../TextGrid/si534.TextGrid
Read from file... ../single_utt/si535.wav
Read from file... ../TextGrid/si535.TextGrid
Read from file... ../single_utt/si537.wav
Read from file... ../TextGrid/si537.TextGrid
Read from file... ../single_utt/si538.wav
Read from file... ../TextGrid/si538.TextGrid
Read from file... ../single_utt/si539.wav
Read from file... ../TextGrid/si539.TextGrid
Read from file... ../single_utt/si540.wav
Read from file... ../TextGrid/si540.TextGrid
Read from file... ../single_utt/si541.wav
Read from file... ../TextGrid/si541.TextGrid
Read from file... ../single_utt/si542.wav
Read from file... ../TextGrid/si542.TextGrid
Read from file... ../single_utt/si543.wav
Read from file... ../TextGrid/si543.TextGrid
Read from file... ../single_utt/si544.wav
Read from file... ../TextGrid/si544.TextGrid
Read from file... ../single_utt/si545.wav
Read from file... ../TextGrid/si545.TextGrid
Read from file... ../single_utt/si546.wav
Read from file... ../TextGrid/si546.TextGrid
Read from file... ../single_utt/si547.wav
Read from file... ../TextGrid/si547.TextGrid
Read from file... ../single_utt/si548.wav
Read from file... ../TextGrid/si548.TextGrid
Read from file... ../single_utt/si549.wav
Read from file... ../TextGrid/si549.TextGrid
Read from file... ../single_utt/si550.wav
Read from file... ../TextGrid/si550.TextGrid
Read from file... ../single_utt/si551.wav
Read from file... ../TextGrid/si551.TextGrid
Read from file... ../single_utt/si552.wav
Read from file... ../TextGrid/si552.TextGrid
Read from file... ../single_utt/si553.wav
Read from file... ../TextGrid/si553.TextGrid
Read from file... ../single_utt/si554.wav
Read from file... ../TextGrid/si554.TextGrid
Read from file... ../single_utt/si555.wav
Read from file... ../TextGrid/si555.TextGrid
Read from file... ../single_utt/si556.wav
Read from file... ../TextGrid/si556.TextGrid
Read from file... ../single_utt/si557.wav
Read from file... ../TextGrid/si557.TextGrid
Read from file... ../single_utt/si558.wav
Read from file... ../TextGrid/si558.TextGrid
Read from file... ../single_utt/si559.wav
Read from file... ../TextGrid/si559.TextGrid
Read from file... ../single_utt/si560.wav
Read from file... ../TextGrid/si560.TextGrid
Read from file... ../single_utt/si561.wav
Read from file... ../TextGrid/si561.TextGrid
Read from file... ../single_utt/si562.wav
Read from file... ../TextGrid/si562.TextGrid
Read from file... ../single_utt/si563.wav
Read from file... ../TextGrid/si563.TextGrid
Read from file... ../single_utt/si564.wav
Read from file... ../TextGrid/si564.TextGrid
Read from file... ../single_utt/si565.wav
Read from file... ../TextGrid/si565.TextGrid
Read from file... ../single_utt/si566.wav
Read from file... ../TextGrid/si566.TextGrid
Read from file... ../single_utt/si567.wav
Read from file... ../TextGrid/si567.TextGrid
Read from file... ../single_utt/si568.wav
Read from file... ../TextGrid/si568.TextGrid
Read from file... ../single_utt/si569.wav
Read from file... ../TextGrid/si569.TextGrid
Read from file... ../single_utt/si570.wav
Read from file... ../TextGrid/si570.TextGrid
Read from file... ../single_utt/si571.wav
Read from file... ../TextGrid/si571.TextGrid
Read from file... ../single_utt/si572.wav
Read from file... ../TextGrid/si572.TextGrid
Read from file... ../single_utt/si573.wav
Read from file... ../TextGrid/si573.TextGrid
Read from file... ../single_utt/si574.wav
Read from file... ../TextGrid/si574.TextGrid
Read from file... ../single_utt/si575.wav
Read from file... ../TextGrid/si575.TextGrid
Read from file... ../single_utt/si576.wav
Read from file... ../TextGrid/si576.TextGrid
Read from file... ../single_utt/si577.wav
Read from file... ../TextGrid/si577.TextGrid
Read from file... ../single_utt/si578.wav
Read from file... ../TextGrid/si578.TextGrid
Read from file... ../single_utt/si579.wav
Read from file... ../TextGrid/si579.TextGrid
Read from file... ../single_utt/si580.wav
Read from file... ../TextGrid/si580.TextGrid
Read from file... ../single_utt/si581.wav
Read from file... ../TextGrid/si581.TextGrid
Read from file... ../single_utt/si583.wav
Read from file... ../TextGrid/si583.TextGrid
Read from file... ../single_utt/si584.wav
Read from file... ../TextGrid/si584.TextGrid
Read from file... ../single_utt/si585.wav
Read from file... ../TextGrid/si585.TextGrid
Read from file... ../single_utt/si586.wav
Read from file... ../TextGrid/si586.TextGrid
Read from file... ../single_utt/si587.wav
Read from file... ../TextGrid/si587.TextGrid
Read from file... ../single_utt/si588.wav
Read from file... ../TextGrid/si588.TextGrid
Read from file... ../single_utt/si589.wav
Read from file... ../TextGrid/si589.TextGrid
Read from file... ../single_utt/si591.wav
Read from file... ../TextGrid/si591.TextGrid
Read from file... ../single_utt/si592.wav
Read from file... ../TextGrid/si592.TextGrid
Read from file... ../single_utt/si593.wav
Read from file... ../TextGrid/si593.TextGrid
Read from file... ../single_utt/si594.wav
Read from file... ../TextGrid/si594.TextGrid
Read from file... ../single_utt/si596.wav
Read from file... ../TextGrid/si596.TextGrid
Read from file... ../single_utt/si597.wav
Read from file... ../TextGrid/si597.TextGrid
Read from file... ../single_utt/si598.wav
Read from file... ../TextGrid/si598.TextGrid
Read from file... ../single_utt/si599.wav
Read from file... ../TextGrid/si599.TextGrid
Read from file... ../single_utt/si600.wav
Read from file... ../TextGrid/si600.TextGrid
Read from file... ../single_utt/sx10.wav
Read from file... ../TextGrid/sx10.TextGrid
Read from file... ../single_utt/sx100.wav
Read from file... ../TextGrid/sx100.TextGrid
Read from file... ../single_utt/sx101.wav
Read from file... ../TextGrid/sx101.TextGrid
Read from file... ../single_utt/sx102.wav
Read from file... ../TextGrid/sx102.TextGrid
Read from file... ../single_utt/sx103.wav
Read from file... ../TextGrid/sx103.TextGrid
Read from file... ../single_utt/sx104.wav
Read from file... ../TextGrid/sx104.TextGrid
Read from file... ../single_utt/sx105.wav
Read from file... ../TextGrid/sx105.TextGrid
Read from file... ../single_utt/sx106.wav
Read from file... ../TextGrid/sx106.TextGrid
Read from file... ../single_utt/sx107.wav
Read from file... ../TextGrid/sx107.TextGrid
Read from file... ../single_utt/sx108.wav
Read from file... ../TextGrid/sx108.TextGrid
Read from file... ../single_utt/sx109.wav
Read from file... ../TextGrid/sx109.TextGrid
Read from file... ../single_utt/sx11.wav
Read from file... ../TextGrid/sx11.TextGrid
Read from file... ../single_utt/sx110.wav
Read from file... ../TextGrid/sx110.TextGrid
Read from file... ../single_utt/sx111.wav
Read from file... ../TextGrid/sx111.TextGrid
Read from file... ../single_utt/sx112.wav
Read from file... ../TextGrid/sx112.TextGrid
Read from file... ../single_utt/sx113.wav
Read from file... ../TextGrid/sx113.TextGrid
Read from file... ../single_utt/sx114.wav
Read from file... ../TextGrid/sx114.TextGrid
Read from file... ../single_utt/sx115.wav
Read from file... ../TextGrid/sx115.TextGrid
Read from file... ../single_utt/sx116.wav
Read from file... ../TextGrid/sx116.TextGrid
Read from file... ../single_utt/sx117.wav
Read from file... ../TextGrid/sx117.TextGrid
Read from file... ../single_utt/sx118.wav
Read from file... ../TextGrid/sx118.TextGrid
Read from file... ../single_utt/sx119.wav
Read from file... ../TextGrid/sx119.TextGrid
Read from file... ../single_utt/sx12.wav
Read from file... ../TextGrid/sx12.TextGrid
Read from file... ../single_utt/sx120.wav
Read from file... ../TextGrid/sx120.TextGrid
Read from file... ../single_utt/sx121.wav
Read from file... ../TextGrid/sx121.TextGrid
Read from file... ../single_utt/sx122.wav
Read from file... ../TextGrid/sx122.TextGrid
Read from file... ../single_utt/sx123.wav
Read from file... ../TextGrid/sx123.TextGrid
Read from file... ../single_utt/sx124.wav
Read from file... ../TextGrid/sx124.TextGrid
Read from file... ../single_utt/sx126.wav
Read from file... ../TextGrid/sx126.TextGrid
Read from file... ../single_utt/sx127.wav
Read from file... ../TextGrid/sx127.TextGrid
Read from file... ../single_utt/sx128.wav
Read from file... ../TextGrid/sx128.TextGrid
Read from file... ../single_utt/sx129.wav
Read from file... ../TextGrid/sx129.TextGrid
Read from file... ../single_utt/sx13.wav
Read from file... ../TextGrid/sx13.TextGrid
Read from file... ../single_utt/sx130.wav
Read from file... ../TextGrid/sx130.TextGrid
Read from file... ../single_utt/sx131.wav
Read from file... ../TextGrid/sx131.TextGrid
Read from file... ../single_utt/sx134.wav
Read from file... ../TextGrid/sx134.TextGrid
Read from file... ../single_utt/sx135.wav
Read from file... ../TextGrid/sx135.TextGrid
Read from file... ../single_utt/sx136.wav
Read from file... ../TextGrid/sx136.TextGrid
Read from file... ../single_utt/sx137.wav
Read from file... ../TextGrid/sx137.TextGrid
Read from file... ../single_utt/sx138.wav
Read from file... ../TextGrid/sx138.TextGrid
Read from file... ../single_utt/sx139.wav
Read from file... ../TextGrid/sx139.TextGrid
Read from file... ../single_utt/sx14.wav
Read from file... ../TextGrid/sx14.TextGrid
Read from file... ../single_utt/sx140.wav
Read from file... ../TextGrid/sx140.TextGrid
Read from file... ../single_utt/sx141.wav
Read from file... ../TextGrid/sx141.TextGrid
Read from file... ../single_utt/sx142.wav
Read from file... ../TextGrid/sx142.TextGrid
Read from file... ../single_utt/sx144.wav
Read from file... ../TextGrid/sx144.TextGrid
Read from file... ../single_utt/sx145.wav
Read from file... ../TextGrid/sx145.TextGrid
